Feat/server side
edgelesssys/ttls pull request #18
Opened 2021-05-04 10:20 UTC by 3u13r

2021-05-05 14:44 UTC, thomasten requested changes

2021-05-05 14:44 UTC, thomasten commented on 3rdparty/mbedtls/ssl_client.c
> +    if( client_auth ){
add a short comment *that* and *why* you inserted this block (beginning with `// EDG: `)

2021-05-05 14:44 UTC, thomasten commented on 3rdparty/mbedtls/ssl_client.c
> +        mbedtls_printf( "%s\n", vrfy_buf );
Why did you change that from
```suggestion
#if !defined(MBEDTLS_X509_REMOVE_INFO)
        char vrfy_buf[512];
#endif

        mbedtls_printf( " failed\n" );

#if !defined(MBEDTLS_X509_REMOVE_INFO)
        mbedtls_x509_crt_verify_info( vrfy_buf, sizeof( vrfy_buf ), "  ! ", flags );

        mbedtls_printf( "%s\n", vrfy_buf );
#endif
```
?

2021-05-05 14:44 UTC, thomasten commented on include/ttls/test_instances.h
> + * Starts a tls test client and waits for it to be ready.
Something like
```suggestion
 * Starts a tls test client that connects to port 9010. The server must already be listening.
```

2021-05-05 14:44 UTC, thomasten commented on include/ttls/mbedtls_socket.h
> +  explicit MbedtlsSocket(const SocketPtr& sock_, bool req_client_auth_);
```suggestion
  MbedtlsSocket(const SocketPtr& sock, bool req_client_auth);
```

2021-05-05 14:44 UTC, thomasten commented on src/dispatcher.cc
> +  const auto& entries = Conf()["tls"]["Egress"];
```suggestion
  const auto& entries = Conf()["tls"]["Outgoing"];
```

2021-05-05 14:44 UTC, thomasten commented on src/dispatcher.cc
> +  const auto& entries = Conf()["tls"]["Ingress"];
```suggestion
  const auto& entries = Conf()["tls"]["Incoming"];
```

2021-05-05 14:44 UTC, thomasten commented on src/dispatcher.cc
> +  const int fd = raw_->Accept4(sockfd, addr, addrlen, flags);
accept may be called with nullptr for addr and addrlen. So we need to declare and pass our own variables here and copy the values if caller did not pass nullptr. Either fix or add TODO

2021-05-05 14:44 UTC, thomasten commented on src/dispatcher_test.cc
> +  EXPECT_EQ(tls_fd, dispatcher.Accept4(tls_fd, &sock_addr, &len, 0));
addr is an out parameter

2021-05-05 14:44 UTC, thomasten commented on src/mbedtls_socket.cc
> +    : sock_(sock), ctr_drbg_{}, entropy_{}, req_client_auth_(req_client_auth_) {
```suggestion
MbedtlsSocket::MbedtlsSocket(const SocketPtr& sock, bool req_client_auth)
    : sock_(sock), ctr_drbg_{}, entropy_{}, req_client_auth_(req_client_auth) {
```

2021-05-05 14:44 UTC, thomasten commented on src/mbedtls_socket.cc
> +  return -1;
```suggestion
```

2021-05-05 17:15 UTC, 3u13r commented on 3rdparty/mbedtls/ssl_client.c
> +        mbedtls_printf( " failed\n  !  mbedtls_x509_crt_parse returned %d\n\n", ret );
I apparently copied the crt_parse from the test server, because I didn't see they were different.

2021-05-06 13:11 UTC, thomasten approved these changes

2021-05-06 13:11 UTC, thomasten commented on src/dispatcher.cc
> +  if (addr != nullptr && addrlen != nullptr) {
check fd first

2021-05-07 09:01 UTC, merged